# .github/workflows/convert-to-pdf.yml

name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'docs/**.md'
      - 'docs/images/**'
      - 'security/**.md'
      - 'security/images/**'
      - 'security/"Score Model ASVS.ods"'
      - '.github/workflows/convert-to-pdf.yml'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p ./pdfs/docs
      - run: mkdir -p ./pdfs/security
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: ./
          output_dir: ./pdfs/
          build_html: false
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: ./docs
          output_dir: ./pdfs/docs/
          images_dir: ./docs/images
          image_import: ./images
          build_html: false
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: ./security
          output_dir: ./pdfs/security/
          images_dir: ./security/images
          image_import: ./images
          build_html: false
      - run: cp ./security/"Score Model ASVS.ods" ./pdfs/security/"Score Model ASVS.ods"
      - uses: actions/upload-artifact@v3
        with:
          name: portfolio
          path: ./pdfs
